
# Include all service compose files
include:
  - ./services/cloudflared/docker-compose.yml
  - ./services/watchtower/docker-compose.yml
  - ./services/portainer/docker-compose.yml
  - ./services/openwebui/docker-compose.yml
  - ./services/excalidraw/docker-compose.yml
  - ./services/affine/docker-compose.yml
  - ./services/docmost/docker-compose.yml
  - ./services/new-api/docker-compose.yml

# Global networks definition - tạo network chính ở đây
networks:
  cloudflare_network:
    name: cloudflare_network
    driver: bridge
    external: false
