networks:
  cloudflare_network:
    external: true

services:
  # OpenWebUI - Chỉ qua Cloudflare tunnel
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    restart: unless-stopped
    networks:
      - cloudflare_network
    ports:
      - "127.0.0.1:3000:8080"
    volumes:
      - ../opt/openwebui/data:/app/backend/data
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - WEBUI_SECRET_KEY=2bef4a2d1139f27683b36219ef677f51825628566b1cac07cb440016010917ea
