
services:
  # Docmost PostgreSQL Database
  docmost_postgres:
    image: postgres:16-alpine
    container_name: docmost_postgres
    restart: unless-stopped
    networks:
      - cloudflare_network
    volumes:
      - ../../data/docmost/postgres:/var/lib/postgresql/data
    env_file:
      - ../../.env      # Global env (priority thấp)
      - .env            # Service env (override global)
    environment:
      - POSTGRES_PASSWORD=${DOCMOST_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    profiles:
      - all
      - docmost

  # Docmost Redis Cache
  docmost_redis:
    image: redis:7-alpine
    container_name: docmost_redis
    restart: unless-stopped
    networks:
      - cloudflare_network
    volumes:
      - ../../data/docmost/redis:/data
    env_file:
      - ../../.env      # Global env (priority thấp)
      - .env            # Service env (override global)
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    profiles:
      - all
      - docmost

  # Docmost Main Server
  docmost:
    image: docmost/docmost:latest
    container_name: docmost_server
    restart: unless-stopped
    networks:
      - cloudflare_network
    ports:
      - "127.0.0.1:3009:3000"
    volumes:
      - ../../data/docmost/data:/app/data
      - ../../data/docmost/uploads:/app/uploads
    env_file:
      - ../../.env      # Global env (priority thấp)
      - .env            # Service env (override global)
    depends_on:
      docmost_postgres:
        condition: service_healthy
      docmost_redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - all
      - docmost
