version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - cloudflare_network
    ports:
      - "127.0.0.1:9443:9443"
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../data/portainer:/data
    env_file:
      - ../../.env      # Global env (priority thấp)
      - .env            # Service env (override global)
    profiles:
      - all
      - portainer

networks:
  cloudflare_network:
    external: true
