networks:
  cloudflare_network:
    driver: bridge

services:
  # Cloudflare Tunnel - Main entry point
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - cloudflare_network
    command: tunnel --no-autoupdate run --token eyJhIjoiNGIxNjA1NDdkNDY0YmZiY2VmYTAyMGM3MzI1NzJkNDciLCJ0IjoiZDY1ZDQwNjctNmRmMS00YmMzLWFhOGMtMDJmMTM4MDIwZmRjIiwicyI6Ik56ZGpZVFZqTXpRdE5XSmpNQzAwWVRkbUxXSXlZbVV0TUdWbU5ESmlNems1WWpsbSJ9
    environment:
      - TZ=Asia/Ho_Chi_Minh
